# Generated by Django 4.1.6 on 2023-02-11 19:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='order', serialize=False, to='product.item', verbose_name='Товар')),
                ('count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Должно быть целое число, большее 0')], verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
