# Generated by Django 4.1.6 on 2023-02-12 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_order_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Код купона')),
                ('percent_off', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100, message='Максимальная скидка - 100%'), django.core.validators.MinValueValidator(1, message='Минимальная скидка - 100%')], verbose_name='Величина скидки (%)')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена (коп)'),
        ),
    ]
