# Generated by Django 4.1.6 on 2023-02-12 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_discount_alter_item_description_alter_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('inclusive', models.BooleanField(default=True, verbose_name='Включено в цену?')),
                ('percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100, message='Максимальная скидка - 100%'), django.core.validators.MinValueValidator(1, message='Минимальная скидка - 100%')], verbose_name='Величина налога (%)')),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
            },
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
