# Generated by Django 4.1.6 on 2023-02-12 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_tax_alter_discount_options_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='product.tax', verbose_name='Налог'),
            preserve_default=False,
        ),
    ]
