# Generated by Django 4.1.6 on 2023-02-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_item_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Российский рубль  '), ('USD', 'Американский доллар'), ('EUR', 'Евро')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
    ]
