# Generated by Django 4.1.6 on 2023-02-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Российский рубль  '), ('USD', 'Американский доллар')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
    ]
